volumes:
  pg_data:
  media:
  static:

services:
  db:
    container_name: foodgram-db
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    container_name: foodgram-backend
    build: ../backend/
    env_file: .env
    depends_on:
      - db
      - frontend
    volumes:
      - static:/backend_static/
      - media:/app/media/
  frontend:
    container_name: foodgram-frontend
    build: ../frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    volumes:
      - static:/staticfiles/
      - media:/media/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend